import type { Types } from 'mongoose';
import { point } from '../../src/lib/model-fields.js';
import type { PlatformSettings } from '../../src/modules/admin/platform-settings.schemas.js';
import type {
  BodyType,
  DeliveryOption,
  FuelType,
  Powertrain,
  Transmission,
  Vehicle,
} from '../../src/modules/vehicles/vehicle.model.js';
import type { DemoCity } from './demo-accounts.js';
import { CITIES } from './places.js';

interface DemoVehicleSpec {
  city: DemoCity;
  suburb: string;
  street: string;
  postcode: string;
  make: string;
  model: string;
  year: number;
  variant: string;
  bodyType: BodyType;
  fuelType: FuelType;
  transmission: Transmission;
  seats: number;
  doors: number;
  powertrain: Powertrain;
  features: string[];
  dailyDollars: number;
  weeklyDiscountPct: number;
  monthlyDiscountPct: number;
  extraKmCents: number;
  /** Left out for unlimited kilometres. */
  kmPerDay?: number;
  tier: 'FLEXIBLE' | 'MODERATE' | 'STRICT';
  instantBook?: boolean;
  petFriendly?: boolean;
  childSeat?: boolean;
  /** A Japanese import with a chassis number instead of a VIN. */
  chassisNo?: string;
  delivery?: { radiusKm: number; feeDollars: number };
  airportFeeDollars?: number;
}

/**
 * 20 demo cars, four in each launch city, covering every body type, fuel type and search filter (plan §9,
 * Days 2–3). Production has no demo cars (plan §16, item 16).
 */
export const DEMO_VEHICLES: DemoVehicleSpec[] = [
  {
    city: 'Auckland',
    suburb: 'Ponsonby',
    street: 'Ponsonby Road',
    postcode: '1011',
    make: 'Toyota',
    model: 'Corolla',
    year: 2021,
    variant: 'GX Hybrid',
    bodyType: 'HATCHBACK',
    fuelType: 'HYBRID',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: { engineCc: 1798, cylinders: 4, description: '1.8L petrol hybrid' },
    features: ['Apple CarPlay', 'Android Auto', 'Reversing camera', 'Adaptive cruise control'],
    dailyDollars: 59,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 20,
    extraKmCents: 35,
    kmPerDay: 250,
    tier: 'FLEXIBLE',
    instantBook: true,
    delivery: { radiusKm: 15, feeDollars: 30 },
    airportFeeDollars: 45,
  },
  {
    city: 'Auckland',
    suburb: 'Takapuna',
    street: 'Hurstmere Road',
    postcode: '0622',
    make: 'Tesla',
    model: 'Model 3',
    year: 2022,
    variant: 'Long Range AWD',
    bodyType: 'SEDAN',
    fuelType: 'EV',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 4,
    powertrain: { evRangeKm: 580, batteryKwh: 75, description: 'Dual motor electric' },
    features: ['Autopilot', 'Glass roof', 'Heated seats', 'Type 2 charging cable'],
    dailyDollars: 129,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 25,
    extraKmCents: 30,
    kmPerDay: 300,
    tier: 'MODERATE',
    airportFeeDollars: 60,
  },
  {
    city: 'Auckland',
    suburb: 'Mount Eden',
    street: 'Dominion Road',
    postcode: '1024',
    make: 'Mazda',
    model: 'CX-5',
    year: 2020,
    variant: 'GSX',
    bodyType: 'SUV',
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: { engineCc: 2488, cylinders: 4, description: '2.5L petrol' },
    features: ['Apple CarPlay', 'Roof rails', 'Reversing camera', 'Blind-spot monitoring'],
    dailyDollars: 89,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 20,
    extraKmCents: 40,
    kmPerDay: 250,
    tier: 'MODERATE',
    instantBook: true,
    childSeat: true,
    delivery: { radiusKm: 20, feeDollars: 35 },
  },
  {
    city: 'Auckland',
    suburb: 'Manukau',
    street: 'Great South Road',
    postcode: '2104',
    make: 'Toyota',
    model: 'Hiace',
    year: 2020,
    variant: 'Minibus',
    bodyType: 'VAN',
    fuelType: 'DIESEL',
    transmission: 'AUTOMATIC',
    seats: 12,
    doors: 4,
    powertrain: { engineCc: 2755, cylinders: 4, description: '2.8L turbo diesel' },
    features: ['Bluetooth', 'Reversing camera', 'Rear air conditioning'],
    dailyDollars: 149,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 15,
    extraKmCents: 55,
    kmPerDay: 250,
    tier: 'STRICT',
    airportFeeDollars: 40,
  },
  {
    city: 'Wellington',
    suburb: 'Te Aro',
    street: 'Cuba Street',
    postcode: '6011',
    make: 'Toyota',
    model: 'Aqua',
    year: 2018,
    variant: 'S',
    bodyType: 'HATCHBACK',
    fuelType: 'HYBRID',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: { engineCc: 1496, cylinders: 4, description: '1.5L petrol hybrid' },
    features: ['Bluetooth', 'Reversing camera', 'Keyless entry'],
    dailyDollars: 45,
    weeklyDiscountPct: 15,
    monthlyDiscountPct: 25,
    extraKmCents: 0,
    tier: 'FLEXIBLE',
    instantBook: true,
    chassisNo: 'NHP10-6712345',
  },
  {
    city: 'Wellington',
    suburb: 'Thorndon',
    street: 'Tinakori Road',
    postcode: '6011',
    make: 'Volkswagen',
    model: 'Golf',
    year: 2021,
    variant: 'Life',
    bodyType: 'HATCHBACK',
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: { engineCc: 1395, cylinders: 4, description: '1.4L turbo petrol' },
    features: ['Apple CarPlay', 'Android Auto', 'Adaptive cruise control'],
    dailyDollars: 65,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 20,
    extraKmCents: 35,
    kmPerDay: 250,
    tier: 'MODERATE',
    airportFeeDollars: 30,
  },
  {
    city: 'Wellington',
    suburb: 'Petone',
    street: 'Jackson Street',
    postcode: '5012',
    make: 'Kia',
    model: 'Niro EV',
    year: 2023,
    variant: 'Earth',
    bodyType: 'SUV',
    fuelType: 'EV',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: { evRangeKm: 460, batteryKwh: 64.8, description: 'Electric' },
    features: ['Apple CarPlay', 'Heated seats', 'Type 2 charging cable', 'Heat pump'],
    dailyDollars: 95,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 20,
    extraKmCents: 30,
    kmPerDay: 300,
    tier: 'MODERATE',
    instantBook: true,
    delivery: { radiusKm: 20, feeDollars: 30 },
  },
  {
    city: 'Wellington',
    suburb: 'Miramar',
    street: 'Park Road',
    postcode: '6022',
    make: 'Toyota',
    model: 'Hilux',
    year: 2019,
    variant: 'SR5',
    bodyType: 'UTE',
    fuelType: 'DIESEL',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 4,
    powertrain: { engineCc: 2755, cylinders: 4, description: '2.8L turbo diesel, 4WD' },
    features: ['4WD', 'Tow bar', 'Canopy'],
    dailyDollars: 99,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 15,
    extraKmCents: 50,
    kmPerDay: 200,
    tier: 'STRICT',
    petFriendly: true,
    airportFeeDollars: 25,
  },
  {
    city: 'Christchurch',
    suburb: 'Riccarton',
    street: 'Riccarton Road',
    postcode: '8011',
    make: 'Suzuki',
    model: 'Swift',
    year: 2020,
    variant: 'GLX',
    bodyType: 'HATCHBACK',
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: { engineCc: 1242, cylinders: 4, description: '1.2L petrol' },
    features: ['Apple CarPlay', 'Bluetooth', 'Reversing camera'],
    dailyDollars: 42,
    weeklyDiscountPct: 15,
    monthlyDiscountPct: 25,
    extraKmCents: 0,
    tier: 'FLEXIBLE',
    instantBook: true,
    airportFeeDollars: 25,
  },
  {
    city: 'Christchurch',
    suburb: 'Merivale',
    street: 'Papanui Road',
    postcode: '8014',
    make: 'Mitsubishi',
    model: 'Outlander PHEV',
    year: 2021,
    variant: 'VRX',
    bodyType: 'SUV',
    fuelType: 'PHEV',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: {
      engineCc: 2360,
      cylinders: 4,
      evRangeKm: 54,
      batteryKwh: 13.8,
      description: '2.4L petrol plug-in hybrid, AWD',
    },
    features: ['AWD', 'Heated seats', 'Sunroof', 'Type 2 charging cable'],
    dailyDollars: 105,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 20,
    extraKmCents: 40,
    kmPerDay: 250,
    tier: 'MODERATE',
    childSeat: true,
    delivery: { radiusKm: 15, feeDollars: 30 },
  },
  {
    city: 'Christchurch',
    suburb: 'Hornby',
    street: 'Main South Road',
    postcode: '8042',
    make: 'Toyota',
    model: 'Estima',
    year: 2017,
    variant: 'Aeras',
    bodyType: 'PEOPLE_MOVER',
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    seats: 8,
    doors: 5,
    powertrain: { engineCc: 2362, cylinders: 4, description: '2.4L petrol' },
    features: ['Power sliding doors', 'Rear air conditioning', 'Reversing camera'],
    dailyDollars: 79,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 20,
    extraKmCents: 45,
    kmPerDay: 250,
    tier: 'MODERATE',
    childSeat: true,
    chassisNo: 'ACR50-7123456',
    airportFeeDollars: 25,
  },
  {
    city: 'Christchurch',
    suburb: 'Addington',
    street: 'Lincoln Road',
    postcode: '8024',
    make: 'Ford',
    model: 'Ranger',
    year: 2022,
    variant: 'XLT',
    bodyType: 'UTE',
    fuelType: 'DIESEL',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 4,
    powertrain: { engineCc: 1996, cylinders: 4, description: '2.0L bi-turbo diesel, 4WD' },
    features: ['4WD', 'Tow bar', 'Tonneau cover', 'Apple CarPlay'],
    dailyDollars: 119,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 15,
    extraKmCents: 50,
    kmPerDay: 200,
    tier: 'STRICT',
    petFriendly: true,
  },
  {
    city: 'Queenstown',
    suburb: 'Frankton',
    street: 'Kawarau Road',
    postcode: '9300',
    make: 'Toyota',
    model: 'RAV4',
    year: 2022,
    variant: 'GXL Hybrid AWD',
    bodyType: 'SUV',
    fuelType: 'HYBRID',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: { engineCc: 2487, cylinders: 4, description: '2.5L petrol hybrid, AWD' },
    features: ['AWD', 'Ski rack', 'Snow chains', 'Apple CarPlay'],
    dailyDollars: 115,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 20,
    extraKmCents: 40,
    kmPerDay: 250,
    tier: 'MODERATE',
    instantBook: true,
    airportFeeDollars: 20,
  },
  {
    city: 'Queenstown',
    suburb: 'Arthurs Point',
    street: 'Arthurs Point Road',
    postcode: '9371',
    make: 'Subaru',
    model: 'Outback',
    year: 2020,
    variant: 'Premium',
    bodyType: 'WAGON',
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: { engineCc: 2498, cylinders: 4, description: '2.5L petrol, AWD' },
    features: ['AWD', 'Ski rack', 'Roof rails', 'Heated seats'],
    dailyDollars: 99,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 20,
    extraKmCents: 40,
    kmPerDay: 250,
    tier: 'MODERATE',
    petFriendly: true,
    delivery: { radiusKm: 15, feeDollars: 25 },
    airportFeeDollars: 25,
  },
  {
    city: 'Queenstown',
    suburb: 'Fernhill',
    street: 'Fernhill Road',
    postcode: '9300',
    make: 'Mazda',
    model: 'MX-5',
    year: 2019,
    variant: 'Limited',
    bodyType: 'CONVERTIBLE',
    fuelType: 'PETROL',
    transmission: 'MANUAL',
    seats: 2,
    doors: 2,
    powertrain: { engineCc: 1998, cylinders: 4, description: '2.0L petrol' },
    features: ['Soft top', 'Bose audio', 'Heated seats'],
    dailyDollars: 109,
    weeklyDiscountPct: 5,
    monthlyDiscountPct: 10,
    extraKmCents: 45,
    kmPerDay: 200,
    tier: 'STRICT',
  },
  {
    city: 'Queenstown',
    suburb: 'Kelvin Heights',
    street: 'Peninsula Road',
    postcode: '9300',
    make: 'Nissan',
    model: 'Leaf',
    year: 2021,
    variant: 'e+',
    bodyType: 'HATCHBACK',
    fuelType: 'EV',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: { evRangeKm: 385, batteryKwh: 62, description: 'Electric' },
    features: ['Apple CarPlay', 'Heated seats', 'Type 2 charging cable'],
    dailyDollars: 69,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 20,
    extraKmCents: 0,
    tier: 'FLEXIBLE',
    instantBook: true,
    airportFeeDollars: 20,
  },
  {
    city: 'Rotorua',
    suburb: 'Glenholme',
    street: 'Fenton Street',
    postcode: '3010',
    make: 'Toyota',
    model: 'Prius',
    year: 2020,
    variant: 'Hybrid',
    bodyType: 'HATCHBACK',
    fuelType: 'HYBRID',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: { engineCc: 1798, cylinders: 4, description: '1.8L petrol hybrid' },
    features: ['Bluetooth', 'Reversing camera', 'Adaptive cruise control'],
    dailyDollars: 52,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 20,
    extraKmCents: 30,
    kmPerDay: 250,
    tier: 'FLEXIBLE',
    instantBook: true,
    airportFeeDollars: 20,
  },
  {
    city: 'Rotorua',
    suburb: 'Lynmore',
    street: 'Te Ngae Road',
    postcode: '3010',
    make: 'Hyundai',
    model: 'Kona Electric',
    year: 2021,
    variant: 'Elite',
    bodyType: 'SUV',
    fuelType: 'EV',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: { evRangeKm: 449, batteryKwh: 64, description: 'Electric' },
    features: ['Apple CarPlay', 'Heated seats', 'Head-up display', 'Type 2 charging cable'],
    dailyDollars: 79,
    weeklyDiscountPct: 10,
    monthlyDiscountPct: 20,
    extraKmCents: 30,
    kmPerDay: 300,
    tier: 'MODERATE',
    delivery: { radiusKm: 10, feeDollars: 20 },
  },
  {
    city: 'Rotorua',
    suburb: 'Ngongotahā',
    street: 'Ngongotahā Road',
    postcode: '3010',
    make: 'Honda',
    model: 'Jazz',
    year: 2018,
    variant: 'Hybrid',
    bodyType: 'HATCHBACK',
    fuelType: 'HYBRID',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 5,
    powertrain: { engineCc: 1496, cylinders: 4, description: '1.5L petrol hybrid' },
    features: ['Bluetooth', 'Magic seats', 'Keyless entry'],
    dailyDollars: 39,
    weeklyDiscountPct: 15,
    monthlyDiscountPct: 25,
    extraKmCents: 0,
    tier: 'FLEXIBLE',
    petFriendly: true,
    chassisNo: 'GP5-3012345',
  },
  {
    city: 'Rotorua',
    suburb: 'Rotorua Central',
    street: 'Tutanekai Street',
    postcode: '3010',
    make: 'BMW',
    model: '320i',
    year: 2022,
    variant: 'M Sport',
    bodyType: 'SEDAN',
    fuelType: 'PETROL',
    transmission: 'AUTOMATIC',
    seats: 5,
    doors: 4,
    powertrain: { engineCc: 1998, cylinders: 4, description: '2.0L turbo petrol' },
    features: ['Apple CarPlay', 'Leather seats', 'Heated seats', 'Parking assistant'],
    dailyDollars: 139,
    weeklyDiscountPct: 5,
    monthlyDiscountPct: 15,
    extraKmCents: 60,
    kmPerDay: 200,
    tier: 'STRICT',
    airportFeeDollars: 30,
  },
];

/** The demo applicant's first listing, waiting for review (not live, so not in the 20). */
export const REVIEW_VEHICLE: DemoVehicleSpec = {
  city: 'Auckland',
  suburb: 'Parnell',
  street: 'Parnell Road',
  postcode: '1052',
  make: 'Toyota',
  model: 'Highlander',
  year: 2019,
  variant: 'Limited',
  bodyType: 'SUV',
  fuelType: 'PETROL',
  transmission: 'AUTOMATIC',
  seats: 7,
  doors: 5,
  powertrain: { engineCc: 3456, cylinders: 6, description: '3.5L V6 petrol' },
  features: ['Third-row seats', 'Roof rails', 'Reversing camera'],
  dailyDollars: 119,
  weeklyDiscountPct: 10,
  monthlyDiscountPct: 20,
  extraKmCents: 45,
  kmPerDay: 250,
  tier: 'MODERATE',
  childSeat: true,
};

export type DemoVehicle = Omit<Vehicle, 'createdAt' | 'updatedAt'>;

const DAY_MS = 24 * 60 * 60 * 1000;

function monthsFrom(now: Date, months: number): Date {
  const date = new Date(now);
  date.setUTCMonth(date.getUTCMonth() + months);
  return date;
}

function slugify(text: string): string {
  return text
    .normalize('NFD')
    .replace(/\p{M}/gu, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

/** Placeholder images until uploads go through Cloudinary (plan §9, Days 8–11). Demo data only. */
function placeholderImage(width: number, height: number, text: string): string {
  return `https://placehold.co/${width}x${height}/0254C2/FFFFFF/webp?text=${encodeURIComponent(text)}`;
}

/** Everything a demo listing needs, for the car at `index` in DEMO_VEHICLES. */
export function buildDemoVehicle(
  spec: DemoVehicleSpec,
  index: number,
  hostId: Types.ObjectId,
  settings: PlatformSettings,
  now: Date,
): DemoVehicle {
  const city = CITIES.find((candidate) => candidate.name === spec.city);
  const suburb = city?.suburbs?.find((candidate) => candidate.name === spec.suburb);
  if (!city || !suburb) throw new Error(`Unknown demo location ${spec.suburb}, ${spec.city}`);

  const number = index + 1;
  const title = `${spec.year} ${spec.make} ${spec.model}`;
  // Spread cars in the same suburb a little, so they don't share one map point.
  const location = point(suburb.lng + ((index % 3) - 1) * 0.002, suburb.lat + ((index % 2) - 0.5) * 0.002);
  const wofExpiry = monthsFrom(now, 3 + (index % 9));
  const regoExpiry = monthsFrom(now, 2 + (index % 11));
  const needsRuc = spec.fuelType === 'DIESEL' || spec.fuelType === 'EV' || spec.fuelType === 'PHEV';

  const deliveryOptions: DeliveryOption[] = [
    {
      type: 'PICKUP',
      label: `Pickup in ${spec.suburb}`,
      address: {
        street: spec.street,
        suburb: spec.suburb,
        city: spec.city,
        region: city.region,
        postcode: spec.postcode,
        location,
      },
      feeCents: 0,
      instructions: 'Off-street parking at the front. Message me when you’re 10 minutes away.',
    },
  ];
  if (spec.delivery) {
    deliveryOptions.push({
      type: 'DELIVERY',
      label: `Delivery around ${spec.city}`,
      feeCents: spec.delivery.feeDollars * 100,
      radiusKm: spec.delivery.radiusKm,
    });
  }
  if (spec.airportFeeDollars && city.airport) {
    deliveryOptions.push({
      type: 'AIRPORT',
      label: city.airport.name,
      airportCode: city.airport.code,
      feeCents: spec.airportFeeDollars * 100,
      instructions: 'I’ll meet you outside the arrivals hall. I’ll message you when I’m there.',
    });
  }

  return {
    hostId,
    slug: slugify(`${title} ${spec.city}`),
    regoPlate: `DEMO${String(number).padStart(2, '0')}`,
    vin: spec.chassisNo ? undefined : `RVDEM${String(number).padStart(12, '0')}`,
    chassisNo: spec.chassisNo,
    make: spec.make,
    model: spec.model,
    year: spec.year,
    variant: spec.variant,
    transmission: spec.transmission,
    bodyType: spec.bodyType,
    fuelType: spec.fuelType,
    seats: spec.seats,
    doors: spec.doors,
    features: spec.features,
    wofExpiry,
    regoExpiry,
    rucValidToKm: needsRuc ? 60_000 + index * 3_500 : undefined,
    powertrain: spec.powertrain,
    fuelPolicy: 'SAME_LEVEL',
    kmAllowancePerDay: spec.kmPerDay,
    unlimitedKm: spec.kmPerDay === undefined,
    petFriendly: spec.petFriendly ?? false,
    childSeat: spec.childSeat ?? false,
    ownerIsHost: true,
    pricing: {
      dailyCents: spec.dailyDollars * 100,
      weeklyDiscountPct: spec.weeklyDiscountPct,
      monthlyDiscountPct: spec.monthlyDiscountPct,
      extraKmCents: spec.extraKmCents,
    },
    rules: {
      minDays: 1,
      maxDays: 30,
      minNoticeHours: spec.instantBook ? 4 : 12,
      bufferHours: 2,
      instantBook: spec.instantBook ?? false,
      cancellationTier: spec.tier,
    },
    status: 'ACTIVE',
    onboardingStep: 6,
    location,
    suburb: spec.suburb,
    city: spec.city,
    region: city.region,
    rating: { avg: 0, count: 0 },
    tripCount: 0,
    bookingSeq: 0,
    photos: settings.vehicles.requiredPhotoAngles.map((angle, order) => ({
      type: angle,
      url: placeholderImage(1600, 1067, `${title} - ${angle.toLowerCase()}`),
      order,
      qualityFlag: 'OK',
      status: 'APPROVED',
    })),
    documents: [
      { type: 'REGO', expiry: regoExpiry },
      { type: 'WOF', expiry: wofExpiry },
      { type: 'INSURANCE', expiry: new Date(now.getTime() + 300 * DAY_MS) },
    ].map((document) => ({
      type: document.type as 'REGO' | 'WOF' | 'INSURANCE',
      url: placeholderImage(1200, 1600, `Demo ${document.type} document`),
      expiry: document.expiry,
      status: 'VERIFIED',
    })),
    deliveryOptions,
    recurringRules: [],
    maintenanceReminders: [],
  };
}
