import type { EmailTemplateName, EmailTemplateProps } from './index.js';

/**
 * Sample details for every email, for `npm run email:dev` (plan §7). Adding a template to emailTemplates
 * without adding it here is a type error.
 */
export const previewProps: { [Name in EmailTemplateName]: EmailTemplateProps<Name> } = {
  welcome: { firstName: 'Kiri', browseUrl: 'https://www.rentovroom.com/cars' },
  verifyEmail: { firstName: 'Kiri', verifyUrl: 'https://www.rentovroom.com/verify-email?token=preview' },
  resetPassword: { firstName: 'Kiri', resetUrl: 'https://www.rentovroom.com/reset-password?token=preview' },
  passwordChanged: { firstName: 'Kiri', resetUrl: 'https://www.rentovroom.com/forgot-password' },
  confirmEmailChange: {
    firstName: 'Kiri',
    newEmail: 'kiri.new@example.co.nz',
    confirmUrl: 'https://www.rentovroom.com/confirm-email-change?token=preview',
  },
  emailChanged: {
    firstName: 'Kiri',
    newEmail: 'kiri.new@example.co.nz',
    resetUrl: 'https://www.rentovroom.com/forgot-password',
  },
  mfaChanged: {
    firstName: 'Kiri',
    change: 'DEVICE_ADDED',
    deviceName: 'Work phone',
    resetUrl: 'https://www.rentovroom.com/forgot-password',
  },
  staffInvite: {
    firstName: 'Kiri',
    invitedBy: 'Aroha',
    acceptUrl: 'https://www.rentovroom.com/admin/invite?token=preview',
    validDays: 7,
  },
  supportTicketReceived: { name: 'Kiri', ref: 'ST-4HX8PA', subject: 'Changing my pick-up time' },
  hostApplicationReceived: { firstName: 'Kiri', listUrl: 'https://www.rentovroom.com/host/vehicles/new' },
  hostApplicationDecision: {
    firstName: 'Kiri',
    approved: true,
    url: 'https://www.rentovroom.com/host',
  },
  listingSubmitted: {
    firstName: 'Kiri',
    vehicleTitle: '2022 Toyota RAV4',
    url: 'https://www.rentovroom.com/host/vehicles/preview',
  },
  listingDecision: {
    firstName: 'Kiri',
    vehicleTitle: '2022 Toyota RAV4',
    decision: 'CHANGES_REQUESTED',
    notes: 'The boot photo is blurry. Could you take it again in daylight?',
    url: 'https://www.rentovroom.com/host/vehicles/preview',
  },
  bookingRequestHost: {
    firstName: 'Hana',
    guestFirstName: 'Kiri',
    ref: 'RV-7K2Q9M',
    vehicleTitle: '2022 Toyota RAV4',
    start: 'Mon, 12 Oct 2026, 10:00 am',
    end: 'Thu, 15 Oct 2026, 10:00 am',
    pickupLabel: 'Mount Eden, Auckland',
    payout: '$213.60',
    expiresAt: 'Sun, 4 Oct 2026, 2:30 pm',
    url: 'https://www.rentovroom.com/host/bookings/RV-7K2Q9M',
  },
  bookingRequestSent: {
    firstName: 'Kiri',
    hostFirstName: 'Hana',
    ref: 'RV-7K2Q9M',
    vehicleTitle: '2022 Toyota RAV4',
    start: 'Mon, 12 Oct 2026, 10:00 am',
    end: 'Thu, 15 Oct 2026, 10:00 am',
    total: '$338.70',
    expiresAt: 'Sun, 4 Oct 2026, 2:30 pm',
    url: 'https://www.rentovroom.com/trips/RV-7K2Q9M',
  },
  bookingVerificationReview: {
    firstName: 'Kiri',
    ref: 'RV-7K2Q9M',
    vehicleTitle: '2022 Toyota RAV4',
    start: 'Mon, 12 Oct 2026, 10:00 am',
    end: 'Thu, 15 Oct 2026, 10:00 am',
    total: '$338.70',
    expiresAt: 'Sun, 4 Oct 2026, 2:30 pm',
    url: 'https://www.rentovroom.com/trips/RV-7K2Q9M',
  },
  bookingConfirmedGuest: {
    firstName: 'Kiri',
    hostFirstName: 'Hana',
    hostPhone: '+64 21 123 4567',
    ref: 'RV-7K2Q9M',
    vehicleTitle: '2022 Toyota RAV4',
    start: 'Mon, 12 Oct 2026, 10:00 am',
    end: 'Thu, 15 Oct 2026, 10:00 am',
    pickupLabel: 'Collect from the host',
    pickupAddress: '12 Dominion Road, Mount Eden, Auckland 1024',
    pickupInstructions: 'Off-street parking at the front. Message me when you’re 10 minutes away.',
    total: '$338.70',
    url: 'https://www.rentovroom.com/trips/RV-7K2Q9M',
    verifyEmailUrl: 'https://www.rentovroom.com/account/settings',
  },
  bookingConfirmedHost: {
    firstName: 'Hana',
    guestFirstName: 'Kiri',
    guestPhone: '+64 22 765 4321',
    ref: 'RV-7K2Q9M',
    vehicleTitle: '2022 Toyota RAV4',
    start: 'Mon, 12 Oct 2026, 10:00 am',
    end: 'Thu, 15 Oct 2026, 10:00 am',
    pickupLabel: 'Collect from the host',
    payout: '$213.60',
    url: 'https://www.rentovroom.com/host/bookings/RV-7K2Q9M',
  },
  bookingDeclined: {
    firstName: 'Kiri',
    vehicleTitle: '2022 Toyota RAV4',
    start: 'Mon, 12 Oct 2026, 10:00 am',
    outcome: 'DECLINED',
    searchUrl: 'https://www.rentovroom.com/cars',
  },
  requestExpiredHost: {
    firstName: 'Hana',
    guestFirstName: 'Kiri',
    vehicleTitle: '2022 Toyota RAV4',
    url: 'https://www.rentovroom.com/host/bookings',
  },
  bookingCancelled: {
    firstName: 'Kiri',
    audience: 'GUEST',
    cancelledBy: 'GUEST',
    ref: 'RV-7K2Q9M',
    vehicleTitle: '2022 Toyota RAV4',
    start: 'Mon, 12 Oct 2026, 10:00 am',
    end: 'Thu, 15 Oct 2026, 10:00 am',
    refund: '$205.20',
    fee: '$133.50',
    url: 'https://www.rentovroom.com/trips/RV-7K2Q9M',
  },
  paymentReceipt: {
    firstName: 'Kiri',
    ref: 'RV-7K2Q9M',
    vehicleTitle: '2022 Toyota RAV4',
    start: 'Mon, 12 Oct 2026, 10:00 am',
    end: 'Thu, 15 Oct 2026, 10:00 am',
    paidAt: 'Fri, 2 Oct 2026, 2:30 pm',
    method: 'Visa ending 4242',
    lines: [
      { label: '3 days × $89', amount: '$267.00' },
      { label: 'Service fee', amount: '$26.70' },
      { label: 'Basic protection (3 × $15)', amount: '$45.00' },
    ],
    total: '$338.70',
    gst: '$44.18',
    legalName: 'Rento Vroom',
    url: 'https://www.rentovroom.com/trips/RV-7K2Q9M',
  },
  paymentFailed: {
    firstName: 'Kiri',
    vehicleTitle: '2022 Toyota RAV4',
    reason: 'your card was declined',
    retryUrl: 'https://www.rentovroom.com/trips/RV-7K2Q9M',
    holdUntil: '2:45 pm',
  },
  refundIssued: {
    firstName: 'Kiri',
    ref: 'RV-7K2Q9M',
    vehicleTitle: '2022 Toyota RAV4',
    amount: '$205.20',
    url: 'https://www.rentovroom.com/trips/RV-7K2Q9M',
  },
};
